{% set org = "tdegeus" %}
{% set name = "FrictionQPotSpringBlock" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 726e80959b4fbe8aa115eb831203558cb5a5edc0092aaa86e179e7bb4e9f0510

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - setuptools_scm
        - xtensor
        - qpot
        - goosefem
      run:
        - xtensor
        - qpot
        - goosefem

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/Line1d.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\Line1d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - python
        - pip
        - setuptools_scm
        - xtensor-python
        - numpy
        - qpot
        - goosefem
      run:
        - python

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Spring-block friction model.
  description: Spring-block friction model.
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
