{% set org = "tdegeus" %}
{% set name = "FrictionQPotSpringBlock" %}
{% set version = "0.22.7" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c7b50ba01e1af6b49c5f5bd2cc87b529129bfbb37d2cf086e1fc33d54d11b946

build:
  number: 1

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - gmattensor >0.10.1
        - goosefem
        - prrng >=1.7.1
        - xtensor >=0.24.6
      run:
        - gmattensor >0.10.1
        - goosefem
        - prrng >=1.7.1
        - xtensor >=0.24.6

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/Line1d.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\Line1d.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      skip: true  # [python_impl == 'pypy']

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja
      host:
        - gmattensor >0.10.1
        - goosefem
        - numpy *
        - pip
        - prrng >=1.7.1
        - pybind11
        - pybind11-abi
        - python
        - python-prrng >=1.10.1
        - scikit-build
        - setuptools_scm
        - xtensor >=0.24.6
        - xtensor-python
      run:
        - numpy *
        - python
        - python-prrng >=1.10.1

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
        - python -c "import {{ name }}; assert {{ name }}.version() == '{{ version }}'"
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Spring-block friction model.
  description: Spring-block friction model.
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
